// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHLXM7vyuOAQ3ya_jv1eAK4xOl1wGOjAU',
    appId: '1:601256712185:web:66533fd931da6e3eb70f28',
    messagingSenderId: '601256712185',
    projectId: 'fruit-app-e8442',
    authDomain: 'fruit-app-e8442.firebaseapp.com',
    storageBucket: 'fruit-app-e8442.firebasestorage.app',
    measurementId: 'G-NDFQGL2ZN6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4vCeFfeD4HyMrW0kDq1TmPmAwc39_3fY',
    appId: '1:601256712185:android:1e99fcd42af3e5dbb70f28',
    messagingSenderId: '601256712185',
    projectId: 'fruit-app-e8442',
    storageBucket: 'fruit-app-e8442.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDllhcJPZ1lWuAXM7e-ktNqnr_4TYD-k58',
    appId: '1:601256712185:ios:1b2658f8630022a7b70f28',
    messagingSenderId: '601256712185',
    projectId: 'fruit-app-e8442',
    storageBucket: 'fruit-app-e8442.firebasestorage.app',
    androidClientId: '601256712185-bp85he13curai5k6kesih1dv32nicbpt.apps.googleusercontent.com',
    iosClientId: '601256712185-72hni6bpbp852f3v4gjj9fv8a899h2ja.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitsAppDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDllhcJPZ1lWuAXM7e-ktNqnr_4TYD-k58',
    appId: '1:601256712185:ios:87718b0f1efcd828b70f28',
    messagingSenderId: '601256712185',
    projectId: 'fruit-app-e8442',
    storageBucket: 'fruit-app-e8442.firebasestorage.app',
    androidClientId: '601256712185-bp85he13curai5k6kesih1dv32nicbpt.apps.googleusercontent.com',
    iosClientId: '601256712185-869otd426a2osq8uk563frg80l2016kb.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitsAppDashboard.RunnerTests',
  );
}
